tap "go-delve/delve"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "anyenv"
brew "brew-cask-completion"
brew "gh"
brew "ghq"
brew "git"
brew "git-secrets"
brew "go"
brew "golang-migrate"
brew "imagemagick"
brew "jq"
brew "mysql@5.6", restart_service: true
brew "p7zip"
brew "peco"
brew "readline", link: true
brew "postgresql", restart_service: true
brew "sqlite"
brew "rbenv"
brew "ruby"
brew "telnet"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh"
brew "heroku/brew/heroku"
cask "alfred"
cask "deepl"
