memodir = "~/Dropbox/memo"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "/Users/taiki/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
